language: lisp

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl

# either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi     

# this bit is just testing that travis correctly sets up ASDF to find
# systems placed somewhere within ~/lisp. You can remove this section
# in your own .travis.yml file.
before_script:
  - echo "(defsystem :dummy-cl-travis-system)" > ~/lisp/dummy-cl-travis-system.asd

script:
  # clone lispn as of now (2015/3/1). this will be removed when the next quicklisp release contains lispn
  - git clone git@github.com:guicho271828/lisp-namespace.git ~/lisp/lisp-namespace
  - cl --load testscr.lisp &> out
  - cat out
  # 'Fail: 0' cause the yaml parser error, so I just used the wildecard
  - grep 'Fail. 0' out
 